stages:
  - stage: One
    jobs:
      - job: JobOne
        steps:
          - bash: |
              echo "##vso[task.setvariable variable=one;isOutput=true]One"
            name: variable
  - stage: Two
    jobs:
      - job: JobTwo
        variables: 
          - name: test
            value: $[dependencies.One.outputs['JobOne.variable.One']]
        steps:
          - template: ./step.yaml
            parameters:
              version: ${{ variable.test }}