stages:
  - stage: One
    jobs:
      - job: JobOne
        steps:
          - bash: |
              echo "##vso[task.setvariable variable=one;isOutput=true]One"
            name: variable
  - stage: Two
    variables: 
      test: $[stageDependencies.One.JobOne.outputs['variable.One']]
    jobs:
      - job: JobTwo
        variables:
          inJob: ${{ variables.test }}
        steps:
          - bash: |
              echo "$(inJob)"
            name: variable