stages:
  - stage: One
    jobs:
      - job: JobOne
        steps:
          - bash: |
              echo "##vso[task.setvariable variable=one;isOutput=true]One"
            name: variable
  - stage: Two
    variables: 
      - name: test
        value: $[stageDependencies.One.JobOne.outputs['variable.One']]
    jobs:
      - job: JobTwo
        steps:
          - template: ./step.yaml
            parameters:
              version: $(variables.test)